# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: GSETLang.GSET
PackageVersion: 3.3.0
PackageLocale: en-US
Publisher: GSET Team
PublisherUrl: https://github.com/Crazygiscool/GSETLang
PackageName: GSET
PackageUrl: https://github.com/Crazygiscool/GSETLang
License: MIT OR Apache-2.0
ShortDescription: Generic Syntax Extension Tool - write in any language syntax, compile to any language
Description: GSET (Generic Syntax Extension Tool) is a transpiler that allows you to write code using any language's syntax and compile it to run on any target language's runtime.
Moniker: gset
Tags:
- transpiler
- compiler
- syntax
- gset
ManifestType: defaultLocale
ManifestVersion: 1.6.0
