# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: GSETLang.GSET
PackageVersion: 3.3.0
Installers:
- Architecture: x64
  InstallerType: zip
  NestedInstallerType: portable
  NestedInstallerFiles:
  - RelativeFilePath: gset.exe
    PortableCommandAlias: gset
  InstallerUrl: https://github.com/Crazygiscool/GSETLang/releases/download/v3.3.0/gset-windows-amd64.zip
  InstallerSha256: a301d40214b02e7dff282f62f7b43fe45edbd2892b08c78d362470661d9c3298
ManifestType: installer
ManifestVersion: 1.6.0
